---
# Small suite of smoke tests to execute to ensure that the playbook has deployed as expected

- meta: flush_handlers
  tags:
    - smoke-tests

- name: Make sure packs are reloaded
  become: yes
  command: st2ctl reload --register-all
  changed_when: no
  tags:
    - smoke-tests

- name: st2 installed
  command: st2 --version
  changed_when: no
  tags:
    - smoke-tests

- name: get authentication token
  command: st2 auth {{ st2_auth_username }} -p {{ st2_auth_password }} -t
  register: st2_token
  changed_when: no
  tags:
    - smoke-tests

- name: Ensuring action runners are listening before proceeding
  shell: cat /var/log/st2/st2actionrunner.*.log | grep amqp
  register: output
  until: output.stdout_lines|length > 1
  retries: 5
  changed_when: no
  tags:
    - smoke-tests

- name: st2 run core.local -- date -R
  command: st2 run core.local -- date -R
  environment:
    ST2_AUTH_TOKEN: "{{ st2_token.stdout }}"
  changed_when: no
  tags:
    - smoke-tests

- name: Check web-ui is up
  uri:
    url: https://localhost/
    validate_certs: no
  changed_when: no
  tags:
    - smoke-tests

- name: Generate st2api key
  command: st2 apikey create -k
  environment:
    ST2_AUTH_TOKEN: "{{ st2_token.stdout }}"
  register: st2_api_key
  changed_when: no
  no_log: true
  tags:
    - smoke-tests

- name: st2chatops smoketests for "SLACK"
  include: >
    st2chatops_smoketests.yml
    ST2_AUTH_TOKEN={{ st2_token.stdout }}
    st2chatops_api_key={{ st2_api_key.stdout  }}
    st2chatops_hubot_adapter=slack
    st2chatops_config={'HUBOT_SLACK_TOKEN':'{{ hubot_token }}'}
  when: hubot_token is defined
  tags:
    - smoke-tests
