- name: Set variables and hubot adapter settings
  set_fact:
    st2chatops_hubot_adapter: "{{ st2chatops_hubot_adapter }}"
    st2chatops_config: "{{ st2chatops_config }}"
  changed_when: no
  no_log: true
  tags:
    - smoke-tests

- name: Comment existing hubot adapters in "/opt/stackstorm/chatops/st2chatops.env"
  become: yes
  replace:
    dest: /opt/stackstorm/chatops/st2chatops.env
    regexp: '^(export HUBOT_ADAPTER=.*)'
    replace: '# \1'
  changed_when: no
  tags:
    - smoke-tests

- name: Update "{{ st2chatops_hubot_adapter|upper }}" adapter
  become: yes
  replace:
    dest: /opt/stackstorm/chatops/st2chatops.env
    regexp: '^# (export HUBOT_ADAPTER={{ st2chatops_hubot_adapter }})$'
    replace: '\1'
  changed_when: no
  tags:
    - smoke-tests

- name: Configure "{{ st2chatops_hubot_adapter|upper }}" settings
  become: yes
  ini_file:
    dest: /opt/stackstorm/chatops/st2chatops.env
    section: null
    option: 'export {{ _conf_option.key }}'
    value: '{{ _conf_option.value }}'
    no_extra_spaces: yes
  with_dict: '{{ st2chatops_config }}'
  loop_control:
    loop_var: _conf_option
  no_log: true
  notify: restart st2chatops
  tags:
    - smoke-tests

- meta: flush_handlers
  tags:
    - smoke-tests

- name: Verify st2chatops using bin/hubot
  command: "timeout 10 bin/hubot"
  args:
    chdir: "/opt/stackstorm/chatops/"
  register: test_output
  failed_when: "'{{ st2chatops_hubot_adapter|title }} client now connected' not in test_output.stdout or 'DEBUG Added command: st2 list' not in test_output.stdout"
  changed_when: no
  tags:
    - smoke-tests

- name: TEARDOWN Comment "SLACK" hubot adapters in "st2chatops.env"
  become: yes
  replace:
    dest: /opt/stackstorm/chatops/st2chatops.env
    regexp: '^(export HUBOT_ADAPTER=slack)'
    replace: '# \1'
  changed_when: no
  tags:
    - smoke-tests

- name: TEARDOWN Uncomment "SHELL" adapter
  become: yes
  replace:
    dest: /opt/stackstorm/chatops/st2chatops.env
    regexp: '^# (export HUBOT_ADAPTER=shell)$'
    replace: '\1'
  changed_when: no
  tags:
    - smoke-tests
